from __future__ import annotations

"""Terminal-based preference annotation interface for AI-DJ sequence pairs.

Loads a pairs JSON produced by sample_sequences.py, displays each pair of
track sequences, and records which one the annotator prefers. Progress is saved
after every annotation so the session can be interrupted and resumed.

Usage
-----
python annotate.py --pairs pairs.json --output labels.json
python annotate.py --pairs pairs.json --output labels.json --annotator alice
"""

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any


# ── Display helpers ──────────────────────────────────────────────────────────

_BAR_WIDTH = 12


def _energy_bar(energy: float) -> str:
    filled = round(float(energy) * _BAR_WIDTH)
    return "█" * filled + "░" * (_BAR_WIDTH - filled)


def _display_sequence(label: str, steps: list[dict[str, Any]]) -> None:
    width = 62
    print(f"\n  ── SEQUENCE {label} {'─' * (width - 14 - len(label))}")
    for i, step in enumerate(steps):
        if i > 0:
            transition = step.get("transition_type") or "?"
            print(f"\n       ↓ [{transition}]")
        title = step["title"]
        artist = step["artist"]
        genre = step.get("genre") or "?"
        tempo = step.get("tempo", 0.0)
        energy = step.get("energy", 0.0)
        key = step.get("key", "?")
        print(f"\n  {i + 1}. {title}")
        print(f"     {artist}  |  {genre}")
        print(f"     BPM {tempo:5.1f}  |  Energy {_energy_bar(energy)} {energy:.2f}  |  {key}")
    print()


def _print_header(pair_id: int, total: int, remaining_after: int, annotator: str | None) -> None:
    width = 64
    print(f"\n{'═' * width}")
    info = f"  Pair {pair_id + 1} / {total}   [{remaining_after} remaining after this]"
    if annotator:
        info += f"   Annotator: {annotator}"
    print(info)
    print(f"{'═' * width}")


def _print_summary(annotations: list[dict[str, Any]]) -> None:
    total = len(annotations)
    counts: dict[str | None, int] = {}
    for a in annotations:
        pref = a["preference"]
        counts[pref] = counts.get(pref, 0) + 1
    a_count = counts.get("A", 0)
    b_count = counts.get("B", 0)
    skip_count = counts.get(None, 0)
    print(f"\n  Summary: {total} annotated — A={a_count}  B={b_count}  skipped={skip_count}")


# ── Persistence ──────────────────────────────────────────────────────────────

def _load_labels(labels_path: Path) -> list[dict[str, Any]]:
    if labels_path.exists():
        data = json.loads(labels_path.read_text(encoding="utf-8"))
        return data.get("annotations", [])
    return []


def _save_labels(
    labels_path: Path,
    annotations: list[dict[str, Any]],
    pairs_metadata: dict[str, Any],
    annotator: str | None,
) -> None:
    payload = {
        "pairs_metadata": pairs_metadata,
        "annotator_id": annotator or "default",
        "annotations": annotations,
    }
    labels_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


# ── CLI ──────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Annotate preference pairs generated by sample_sequences.py.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--pairs", default="pairs.json", help="Input pairs JSON file.")
    parser.add_argument("--output", default="labels.json", help="Output labels JSON file.")
    parser.add_argument("--annotator", default=None, help="Your name/ID (stored with each label).")
    return parser.parse_args()


# ── Main loop ────────────────────────────────────────────────────────────────

def main() -> None:
    args = parse_args()

    pairs_path = Path(args.pairs)
    if not pairs_path.exists():
        raise FileNotFoundError(f"Pairs file not found: {pairs_path}")

    data = json.loads(pairs_path.read_text(encoding="utf-8"))
    pairs: list[dict[str, Any]] = data["pairs"]
    pairs_metadata: dict[str, Any] = data.get("metadata", {})
    total = len(pairs)

    labels_path = Path(args.output)
    annotations = _load_labels(labels_path)
    annotated_ids: set[int] = {a["pair_id"] for a in annotations}

    remaining = [p for p in pairs if p["pair_id"] not in annotated_ids]

    print(f"\nLoaded {total} pairs. Already annotated: {len(annotated_ids)}. Remaining: {len(remaining)}.")
    print("Commands:  A = prefer Sequence A   B = prefer Sequence B   S = skip   Q = quit\n")

    if not remaining:
        print("Nothing left to annotate.")
        _print_summary(annotations)
        return

    for pair in remaining:
        pair_id: int = pair["pair_id"]
        remaining_after = len(remaining) - (len(annotated_ids) - (total - len(remaining))) - 1

        _print_header(pair_id, total, max(0, remaining_after), args.annotator)
        _display_sequence("A", pair["sequence_a"])
        _display_sequence("B", pair["sequence_b"])

        print(f"  {'─' * 62}")
        print("  Which sequence has better flow and transitions?")

        while True:
            try:
                raw = input("  [A / B / S=skip / Q=quit] > ").strip().upper()
            except (KeyboardInterrupt, EOFError):
                raw = "Q"

            if raw == "Q":
                _save_labels(labels_path, annotations, pairs_metadata, args.annotator)
                print(f"\nSaved {len(annotations)} annotations → {labels_path}")
                _print_summary(annotations)
                return

            if raw in ("A", "B", "S"):
                preference: str | None = None if raw == "S" else raw
                annotations.append(
                    {
                        "pair_id": pair_id,
                        "preference": preference,
                        "annotator_id": args.annotator or "default",
                        "timestamp": datetime.now().isoformat(),
                    }
                )
                annotated_ids.add(pair_id)
                _save_labels(labels_path, annotations, pairs_metadata, args.annotator)
                break

            print("  Please enter A, B, S, or Q.")

    print(f"\nAll pairs annotated! Saved {len(annotations)} annotations → {labels_path}")
    _print_summary(annotations)


if __name__ == "__main__":
    main()
